spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test2_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update),production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true